// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_pMgKutWSYsISdv9uxPgvnImrIcsypI',
    appId: '1:140254510245:web:4bbbdf2d44a35d0664a14c',
    messagingSenderId: '140254510245',
    projectId: 'new-portfolio-f5e6a',
    authDomain: 'new-portfolio-f5e6a.firebaseapp.com',
    storageBucket: 'new-portfolio-f5e6a.firebasestorage.app',
    measurementId: 'G-39GGT2VC2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfePXKiAQdCcZwLGhfkFqDnsCZO7ihik',
    appId: '1:140254510245:android:4835ca9d983842a264a14c',
    messagingSenderId: '140254510245',
    projectId: 'new-portfolio-f5e6a',
    storageBucket: 'new-portfolio-f5e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_c1zqGfu2uHJ4PIIJD2f8lFtxhKx10qA',
    appId: '1:140254510245:ios:44c979f3e406a54c64a14c',
    messagingSenderId: '140254510245',
    projectId: 'new-portfolio-f5e6a',
    storageBucket: 'new-portfolio-f5e6a.firebasestorage.app',
    iosBundleId: 'com.example.runnn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_c1zqGfu2uHJ4PIIJD2f8lFtxhKx10qA',
    appId: '1:140254510245:ios:44c979f3e406a54c64a14c',
    messagingSenderId: '140254510245',
    projectId: 'new-portfolio-f5e6a',
    storageBucket: 'new-portfolio-f5e6a.firebasestorage.app',
    iosBundleId: 'com.example.runnn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF_pMgKutWSYsISdv9uxPgvnImrIcsypI',
    appId: '1:140254510245:web:d425b445234bbf9c64a14c',
    messagingSenderId: '140254510245',
    projectId: 'new-portfolio-f5e6a',
    authDomain: 'new-portfolio-f5e6a.firebaseapp.com',
    storageBucket: 'new-portfolio-f5e6a.firebasestorage.app',
    measurementId: 'G-C6EKP9KRZV',
  );
}
